# Generated by Django 3.0.4 on 2021-09-21 12:45

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('all_country_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('interested_in', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('your_name', models.CharField(blank=True, max_length=255)),
                ('age', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('interested_age', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('education', models.CharField(blank=True, choices=[('College', 'College'), ('High School', 'High School'), ('BAC Level', 'BAC Level'), ('University Diploma', 'University Diploma')], max_length=20)),
                ('about', models.CharField(blank=True, max_length=1000)),
                ('passion', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), default=[], size=None)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('university', models.CharField(blank=True, max_length=255)),
                ('school', models.CharField(blank=True, max_length=255)),
                ('living', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Super', 'Super'), ('User', 'User'), ('Vendor', 'Vendor')], default='User', max_length=10)),
                ('verfication_status', models.BooleanField(default=False)),
                ('registration_status', models.BooleanField(blank=True, default=False)),
                ('otp', models.CharField(blank=True, default='', max_length=255)),
                ('otp_time', models.DateTimeField(auto_now=True)),
                ('user_deactive_status', models.CharField(blank=True, default='', max_length=255)),
                ('user_deactive_reason', models.CharField(blank=True, default='', max_length=255)),
                ('forget_password_key', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('kids', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('drink', models.CharField(blank=True, choices=[('Frequently', 'Frequently'), ('Socially', 'Socially'), ('Never', 'Never')], max_length=10)),
                ('smoke', models.CharField(blank=True, choices=[('Frequently', 'Frequently'), ('Socially', 'Socially'), ('Never', 'Never')], max_length=10)),
                ('religion', models.CharField(blank=True, choices=[('Christian', 'Christian'), ('Buddhist', 'Buddhist'), ('Catholic', 'Catholic'), ('Islam', 'Islam'), ('Atheist', 'Atheist'), ('Hindu', 'Hindu')], max_length=10)),
                ('exercise', models.CharField(blank=True, choices=[('Active', 'Active'), ('Sometimes', 'Sometimes'), ('Almost Never', 'Almost Never')], max_length=20)),
                ('appear_to_other', models.BooleanField(blank=True, default=True)),
                ('time_list', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(blank=True, max_length=100, null=True), blank=True, default=[], size=None)),
                ('cross_user_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, default=[], size=None)),
                ('user', models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='user_profile_pic/')),
                ('is_active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_pic', to='core.User_Profile')),
            ],
        ),
        migrations.CreateModel(
            name='user_block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_status', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10)),
                ('reason', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_going_to_block', to='core.User_Profile')),
                ('user_profile_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_block', to='core.User_Profile')),
            ],
        ),
        migrations.CreateModel(
            name='like_and_dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_status', models.CharField(blank=True, choices=[('Neutral', 'Neutral'), ('Like', 'Like'), ('Super_Like', 'Super_Like'), ('Dislike', 'Dislike')], default='Neutral', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('cross_check_user', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_dislike_profile_going_to_like', to='core.User_Profile')),
                ('user_profile_liked_or_dislike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_dislike_profile', to='core.User_Profile')),
            ],
        ),
    ]
