# Generated by Django 3.0.4 on 2021-09-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
