# Generated by Django 3.0.2 on 2021-10-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_profile_max_interested_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_and_dislike',
            name='profile_status',
            field=models.CharField(blank=True, choices=[('Neutral', 'Neutral'), ('Like', 'Like'), ('Super_like', 'Super_like'), ('Dislike', 'Dislike')], default='Neutral', max_length=10),
        ),
    ]
