# Generated by Django 3.0.2 on 2021-10-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211011_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='manage_read_receipts',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
