# Generated by Django 3.0.2 on 2021-10-16 06:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_profile_manage_read_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='month_later_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 16, 6, 24, 29, 222607, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
