# Generated by Django 3.0.2 on 2021-10-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_profile_month_later_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='power_like_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
