# Generated by Django 3.0.2 on 2021-11-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_profile_power_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='popup_seen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
