# Generated by Django 3.1.4 on 2021-12-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211209_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='package_date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='package_date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
