# Generated by Django 3.1.4 on 2021-12-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211210_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='manage_read_receipts_date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='manage_read_receipts_end_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='manage_read_receipts_payment',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='manage_read_receipts',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
