# Generated by Django 3.1.4 on 2021-12-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20211210_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='manage_read_receipts_end_start',
            new_name='manage_read_receipts_date_end',
        ),
    ]
