# Generated by Django 3.1.4 on 2021-12-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_like_and_dislike_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
