# Generated by Django 3.1.4 on 2022-02-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_profile_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='classic_bonus_2chance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='classic_bonus_guaranteed_match',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='classic_bonus_guaranteed_match_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='classic_bonus_guaranteed_match_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='classic_bonus_love_coach',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='classic_bonus_power_like',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='classic_bonus_power_like_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='classic_bonus_power_like_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='package_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='vip_bonus_love_coach',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='vip_bonus_power_like',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='vip_bonus_power_like_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='vip_bonus_power_like_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='package',
            field=models.CharField(blank=True, choices=[('Classic', 'Classic'), ('Vip', 'Vip')], max_length=10),
        ),
    ]
