# Generated by Django 3.1.4 on 2022-03-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220217_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('Christian', 'Christian'), ('Buddhist', 'Buddhist'), ('Catholic', 'Catholic'), ('Islam', 'Islam'), ('Atheist', 'Atheist'), ('Spirituality', 'Spirituality')], max_length=20),
        ),
    ]
