# Generated by Django 3.1.4 on 2022-03-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20220315_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='drink',
            field=models.CharField(blank=True, choices=[('partener_drink_frequently', 'Frequently'), ('partener_drink_socially', 'Socially'), ('partener_drink_never', 'Never')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='education',
            field=models.CharField(blank=True, choices=[('update_education_college_checkbox', 'College'), ('update_education_highschool_checkbox', 'High School'), ('update_education_BAC_checkbox', 'BAC Level'), ('update_university_checkbox', 'University Diploma')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='exercise',
            field=models.CharField(blank=True, choices=[('partener_exercise_active', 'Active'), ('partener_exercise_sometime', 'Sometimes'), ('partener_exercise_almostNever', 'Almost Never')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('editprofile_gender_checkboxman', 'Male'), ('editprofile_gender_checkboxwoman', 'Female')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='interested_in',
            field=models.CharField(blank=True, choices=[('editprofile_gender_checkboxman', 'Male'), ('editprofile_gender_checkboxwoman', 'Female')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='kids',
            field=models.CharField(blank=True, choices=[('partener_kids_yes', 'Yes'), ('partener_kids_no', 'No')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('Christian', 'Christian'), ('Buddhist', 'Buddhist'), ('Catholic', 'Catholic'), ('Islam', 'Islam'), ('Atheist', 'Atheist'), ('hindui', 'Spirituality')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='smoke',
            field=models.CharField(blank=True, choices=[('partener_drink_frequently', 'Frequently'), ('partener_drink_socially', 'Socially'), ('partener_drink_never', 'Never')], max_length=100),
        ),
    ]
