# Generated by Django 3.1.4 on 2022-06-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20220315_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='package',
            field=models.CharField(blank=True, choices=[('Classic', 'Classic'), ('VIP', 'VIP'), ('Classic Plus', 'Classic Plus'), ('VIP Plus', 'VIP Plus')], default='VIP Plus', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='package_duration',
            field=models.CharField(blank=True, choices=[('1Month', '1Month'), ('3Month', '3Month'), ('6Month', '6Month'), ('15 Days Trial', '15 Days Trial')], default='15 Days Trial', max_length=100),
        ),
    ]
