# Generated by Django 3.1.4 on 2022-06-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20220621_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='remaining_days_in_exp',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
