# Generated by Django 3.1.4 on 2022-07-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20220623_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='remaining_days_in_exp',
            field=models.PositiveSmallIntegerField(blank=True, default=15),
        ),
    ]
