# Generated by Django 3.1.4 on 2022-07-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20220714_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='interested_in',
            field=models.CharField(blank=True, choices=[('editprofile_gender_checkboxman', 'Male'), ('editprofile_gender_checkboxwoman', 'Female'), ('editprofile_gender_checkboxboth', 'Both')], max_length=100),
        ),
    ]
