# Generated by Django 3.1.4 on 2022-07-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20220718_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='country',
        ),
    ]
