# Generated by Django 3.1.4 on 2022-07-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_user_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
