# Generated by Django 3.1.4 on 2022-07-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_like_and_dislike_match_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
