# Generated by Django 3.1.4 on 2022-09-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_user_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='is_banned',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
