# Generated by Django 3.1.4 on 2022-11-22 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_user_profile_is_restored'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(blank=True, max_length=200, null=True)),
                ('kids', models.CharField(blank=True, max_length=100, null=True)),
                ('drink', models.CharField(blank=True, max_length=100, null=True)),
                ('smoke', models.CharField(blank=True, max_length=100, null=True)),
                ('religion', models.CharField(blank=True, max_length=20, null=True)),
                ('exercise', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('interested_age', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('max_height', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('user_profile', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='core.user_profile')),
            ],
        ),
    ]
