# Generated by Django 3.0.2 on 2021-10-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20211018_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='NotificationRoom',
        ),
    ]
