# Generated by Django 3.0.2 on 2021-10-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_remove_notification_notificationroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationroomroom',
            name='notification_room_name',
        ),
    ]
