# Generated by Django 3.1.4 on 2022-09-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Classic', 'Classic'), ('VIP', 'VIP'), ('Classic Plus', 'Classic Plus'), ('VIP Plus', 'VIP Plus')], max_length=100)),
                ('price', models.PositiveSmallIntegerField()),
                ('duration', models.CharField(blank=True, choices=[('1 Month', '1 Month'), ('3 Month', '3 Month'), ('6 Month', '6 Month'), ('15 Days Trial', '15 Days Trial')], max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
