# Generated by Django 3.1.4 on 2022-09-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='duration',
            field=models.CharField(choices=[('1 Month', '1 Month'), ('3 Month', '3 Month'), ('6 Month', '6 Month'), ('15 Days Trial', '15 Days Trial')], max_length=100),
        ),
        migrations.AlterField(
            model_name='packages',
            name='name',
            field=models.CharField(choices=[('Classic', 'Classic'), ('VIP', 'VIP'), ('Classic Plus', 'Classic Plus'), ('VIP Plus', 'VIP Plus')], max_length=100),
        ),
    ]
