# Generated by Django 3.1.4 on 2022-09-08 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_auto_20220908_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='price',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
    ]
