# Generated by Django 3.1.4 on 2022-10-17 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_auto_20220908_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)]),
        ),
    ]
