# Generated by Django 3.1.4 on 2022-10-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_auto_20221017_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
