# Generated by Django 3.0.2 on 2021-10-01 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20210924_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='content',
            new_name='message_text',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='author',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='chat_room',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='participant',
        ),
        migrations.AddField(
            model_name='chat',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, null=True)),
                ('is_enabled', models.BooleanField(blank=True, default=False, null=True)),
                ('is_deleed', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='Room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.ChatRoom'),
        ),
    ]
