# Generated by Django 3.0.2 on 2021-10-08 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_profile_max_interested_age'),
        ('chat', '0004_auto_20211007_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='Room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Room', to='chat.ChatRoom'),
        ),
        migrations.CreateModel(
            name='All_Threads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_as_thread', models.CharField(max_length=100, null=True)),
                ('lastMessage', models.TextField()),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagereceiver', to='core.User_Profile')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagesender', to='core.User_Profile')),
            ],
        ),
    ]
