# Generated by Django 3.0.2 on 2021-10-12 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20211008_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_threads',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 12, 14, 30, 49, 84209, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='all_threads',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
