# Generated by Django 3.0.2 on 2021-11-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20211012_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_threads',
            name='lastMessage_data',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
