# Generated by Django 3.1.4 on 2021-11-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_all_threads_lastmessage_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_threads',
            name='un_seen_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
