# Generated by Django 3.1.4 on 2021-12-01 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211102_1014'),
        ('chat', '0008_all_threads_un_seen_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='block_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_by_user', to='core.user_profile'),
        ),
    ]
