# Generated by Django 3.1.4 on 2021-12-09 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211102_1014'),
        ('chat', '0009_chatroom_block_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='block_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_to', to='core.user_profile'),
        ),
    ]
