# Generated by Django 3.1.4 on 2022-01-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_chatroom_block_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_threads',
            name='un_seen_count1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
