# Generated by Django 3.1.4 on 2022-09-05 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_user_profile_date_of_birth'),
        ('chat', '0013_auto_20220701_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='block_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_blocked', to='core.user_profile'),
        ),
    ]
